<div class="link-menu">
<div class="link-menu-item">
<div class="link-menu-icon"><a href="#"><img alt="" src="/templates/images/lm-icon1.png" /> </a></div>

<div class="link-menu-title"><a href="#">100+ брендов</a></div>
<a href="#">каталог товаров </a></div>

<div class="link-menu-item">
<div class="link-menu-icon"><a href="#"><img alt="" src="/templates/images/lm-icon2.png" /> </a></div>

<div class="link-menu-title"><a href="#">Бесплатная доставка</a></div>
<a href="#">при заказе от 500 грн </a></div>

<div class="link-menu-item">
<div class="link-menu-icon"><a href="#"><img alt="" src="/templates/images/lm-icon3.png" /> </a></div>

<div class="link-menu-title"><a href="#">Возврат товара</a></div>
<a href="#">в течении 14 дней </a></div>

<div class="link-menu-item">
<div class="link-menu-icon"><a href="#"><img alt="" src="/templates/images/lm-icon4.png" /> </a></div>

<div class="link-menu-title"><a href="#">Подарочные карты</a></div>
<a href="#">на весь ассортимент </a></div>

<div class="clear">&nbsp;</div>
</div>
